# fly.toml app configuration file generated for statsgirl on 2023-06-10T15:25:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "statsgirl"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
